version: "3"

services:
  app:
    image: nodejs
    container_name: example_nodejs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: example_mysql
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  db:
    driver: local

networks:
  app-network:
